SELECT TOP (1000) [Id]
      ,[lastname]
      ,[name]
      ,[pnumber]
      ,[date]
      ,[age]
      ,[favfood]
      ,[eat]
      ,[movies]
      ,[tv]
      ,[radio]
  FROM [ResultsP].[dbo].[TablePr]
